### PR TITLE
auto refresh PUID

### PR DESCRIPTION
**Pull request by maxduke**
Enable auto refresh of PUID.

Two new environment variables are added:
- GO_CHATGPT_OPENAI_EMAIL
- GO_CHATGPT_OPENAI_PASSWORD

### CODE REVIEW

**Comment by linweiyuan** [comment]
这样写，`PUID` 并不会更新到

**Comment by zexry619** [comment]
Is this related to the "Failed To Get Arkose Token" issue?

I use Arkose token from fakeopen.

But it still shows the error "Failed To get arkose token"

If this is related to the problem is there a solution for accounts with google login?

**Comment by linweiyuan** [comment]
Not related.

"Failed to get arkose token" -> update `GO_CHATGPT_API_ARKOSE_TOKEN_URL` to `https://arkose-token.tms.im`, this will temporary fix it, but there's no stable solution to fix this so far.

Google login -> have no idea how to do.

**Comment by zexry619** [comment]
It can work fine.

I asked one of the contributors here, there will be an update to fix captcha problems with the captcha resolver.

Can this be realized?

**Comment by zexry619** [comment]
and is this PUID important?

How to get PUID manually?

And what does it actually do?

**Comment by linweiyuan** [comment]
Not sure the captcha resolver, looks complicated, still in discussion.

The PUID is to bypass IP based rate limit (cannot bypass gpt-4 25/3 hours), like a public api with many requests, if you don't have such a volume, PUID can be ignore.

**Comment by linweiyuan** [comment]
No, when you open ChatGPT, F12, you will find it in the `/models` response cookies, no matter normal account, Google or Microsoft.

**Comment by zexry619** [comment]
I see, so I can input this value in my Docker compose?

**Comment by linweiyuan** [comment]
Yes.

**Pull request merged**
